### ISSUE TITLE
Apps and method panel align w/mockups

### ISSUE THREAD

**Issue by dangunter** [kbase/narrative#102]
Remove code and text cell buttons
Search button in style bar
Clicking search button should toggle search text box
Search text box should be fixed position
Add “type:KBaseGenomes.Genome” filtering in search bar
Design iteration on ‘more’ button
turn +/- to …
click anywhere except for icon/title to pulldown
Add filter based on data input/output type

**Comment by briehl** [comment]
I'm working on this now. Just a note that the first line (removing the IPython cell buttons) depends on having #90 done first.

**Comment by briehl** [comment]
Okay, everything else is done here, now, since #90 was finished and closed.
See https://github.com/kbase/narrative/commit/803b2d868c239b7fb7c9bd8f054a2d773223d60b for change that removed buttons.
