### ISSUE TITLE
Jobs panel error dialog

### ISSUE THREAD

**Issue by dangunter** [kbase/narrative#106]
Clean up the error dialog

**Comment by briehl** [comment]
Done(ish) in this commit: https://github.com/kbase/narrative/commit/ec99c488237881f3f9ce6c1e1c2b55fd1f7b0b42

This was a hotfix to get it working for the release a little while ago. I'll clean things up and change that into a separate css rule for the next step.

**Comment by briehl** [comment]
Fixed in this commit: https://github.com/kbase/narrative/commit/5b2ecaee6a67cc73a95cfdab07fcb980a8bb9ab9
Made a 'kb-jobs-error-modal' class that restricts the width of a text element and enforces word wrap to break words.
