### ISSUE TITLE
Narr app cell styling

### ISSUE THREAD

**Issue by dangunter** [kbase/narrative#108]
While running, the left border should turn green
While in an error, the left border should be red
‘Run’ button turns into ‘Cancel’ button while running
Add confirmation dialog before canceling a running job from the method
Restyle more like mockup
two columns of parameters
no more boxy panels, just a simple flow
Include links to example data in the app/method

**Comment by briehl** [comment]
the 'no more boxy panels' part is done.

I'll tackle the following steps (see also #105):
  - While running, the left border should turn green (this is already there while selected, so we need a different visual cue)
  - While in an error, the left border should be red
  - ‘Run’ button turns into ‘Cancel’ button while running
  - Add confirmation dialog before canceling a running job from the method
