### ISSUE TITLE
Data added after logout

### ISSUE THREAD

**Issue by psdehal** [kbase/narrative#115]
A user can "sign out" and still add data to their narrative.

**Comment by briehl** [comment]
That's weird. A "sign out" should redirect to somewhere away from your Narrative, right?

**Comment by psdehal** [comment]
Yeah, I think a redirect would fix the problem. But if there's a weird
token caching issue happening with the data panel, you might still be able
to push the back button and have the same effect.

**Comment by briehl** [comment]
I think this can still happen, and it's related to some session management that Erik brought up in this JIRA ticket: https://atlassian.kbase.us/browse/NAR-238

Now, when logging out from the Narrative, it should redirect properly. However, if you log out from another window, your Narrative backend container isn't getting the memo and maintains your login info, so uploading will likely still work.

Dealing with that ticket the right way will fix this problem.
