### ISSUE TITLE
Change narrative dev install script to curenv-install.sh

### ISSUE THREAD

**Issue by dangunter** [kbase/narrative#123]
The current install script doesn't work if you already are in a virtual env, whereas curenv-install.sh works in both places. It is also cleaner and easier to use. So, rename install.sh to old-install.sh and curenv-install.sh to install.sh. Some of the options from install.sh no longer work, but it's not clear that anybody was using those anyways.

**Comment by dangunter** [comment]
See branch https://github.com/kbase/narrative/tree/dev-install-script

**Comment by briehl** [comment]
This has been merged in, but the deployment script still uses the old one for a little while. Docker seems to complain something or other. I'll fix it up this weekend.
