### ISSUE TITLE
Need page and handling of fatal UI errors

### ISSUE THREAD

**Issue by dangunter** [kbase/narrative#125]
Need to have some sort of "dead end" error page for major fatal errors (not loading needed configs, Workspace/Shock is down, etc.). The occurrence of these errors should be logged to our global narrative logging service (the log proxy running on the narrative host).

**Comment by dangunter** [comment]
Logging of errors (and fatal errors) is done in branch https://github.com/kbase/narrative/tree/dev-status, see commit 1b5d9dd40c7a2585a261ceddf0d4170ceaa4cc0f

**Comment by briehl** [comment]
It looks like, for logging from the front end, we just have to call KBError(source, message) for non-fatal errors and KBFail(source, message) for fatal ones?

**Comment by dangunter** [comment]
almost. KBError, yes. KBFatal is the equivalent. KBFail is the "generic" one they both call.

The method is actually commented in the code!

**Comment by briehl** [comment]
Guess I should've read those instead of skimming their use!
Thanks for this!
