### ISSUE TITLE
Data slide out empty on Safari for narratives with no data

### ISSUE THREAD

**Issue by psdehal** [kbase/narrative#128]
This seems odd. In safari and firefox and chrome, after creating a new narrative, clicking on the add data button, the slide out appears and is empty. 

http://youtu.be/WXBhGPaAnYg

**Comment by aparkin** [comment]
huh... but the little arrow driven slide out works just fine...
Just the big red button fails.
A

On Mon, Jan 12, 2015 at 11:49 AM, psdehal <notifications@github.com> wrote:

> This seems odd. In safari and firefox, after creating a new narrative,
> clicking on the add data button, the slide out appears and is empty.
>
> It doesn't seem to be an issue with Chrome. We can fix this after the 19th.
>
> http://youtu.be/WXBhGPaAnYg
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbase/narrative/issues/128>.
>



-- 
Adam Paul Arkin
Dean A. Richard Newton Memorial Chair
-------------------------------------
Director, Physical Biosciences Division
E.O. Lawrence Berkeley National Laboratory

Professor, Department of Bioengineering
University of California
Berkeley, CA, 94720

CEO/CSO, DOE Systems Biology Knowledgebase, http://kbase.us
Director, Berkeley Synthetic Biology Institute, http://synbio.berkeley.edu
PI and Co-Director, ENIGMA SFA, http://enigma.lbl.gov <http://vimss.lbl.gov>
Investigator, Energy Biosciences Institute,
http://energybiosciencesinstitute.org

Office: 512C Energy Biosciences Building (Berkeley Campus)
Mailing address:
E.O. Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 955-512L
Berkeley, CA 94720

Contact:
W: http://genomics.lbl.gov
V: 510-495-2366
C: 510-206-1389
F: 510-486-6219

Assistant:
Gwyneth A. Terry
V: 510-495-2116
E: GATerry@lbl.gov
-------------------------------------

**Comment by briehl** [comment]
I think I know what that is. I'll fix it.

**Comment by briehl** [comment]
Okay, fixed. This'll go out in the next deploy.

**Comment by briehl** [comment]
Closing this issue. If this problem comes back, please reopen or submit a new one. Thanks!
