### ISSUE TITLE
Data viewer title should be name of item

### ISSUE THREAD

**Issue by dangunter** [kbase/narrative#134]
The title of the data viewer widgets is currently "[Viewer] Data viewer". This makes scanning the page more difficult because you have to look at the un-highlighted contents of the cell to see which data item is actually there. Instead, I suggest, e.g. for a Genome object called `Genome Vibrio_brasiliensis_LMG_20546` that the title be "[Viewer] Genome Vibrio_brasiliensis_LMG_20546"

**Comment by briehl** [comment]
Fixed. It even links out to the landing page. Nice work!
