### ISSUE TITLE
All Narrative cells should be collapsible

### ISSUE THREAD

**Issue by dangunter** [kbase/narrative#135]
Data viewers and apps/methods should be collapsible. One idea is to use the left-hand "gutter" in the narrative canvas for a small grey arrow. Another option would be to roll up the widget on a double-click in the title bar. Another would be to put a "collapse/expand" button (e.g. fa-collapse / fa-expand) next to the garbage can on the right hand side of the title bar.

**Comment by briehl** [comment]
An update here - currently the App and Method cells are collapsible. Output cells are not, and the usual IPython cells (code & markdown) are not either.

Not sure what to do about those. Part of me wants them collapsible for the sake of consistency, but I can see the argument for keeping them open and following the IPython workflow.

**Comment by aparkin** [comment]
Ultimately I think we need them all Collapsible. I would love to see documents that are very clear when collapsed: 

Markdown might lead to high level chapters.

1. Introduction
2. Comparative Analysis
3. Modeling
4. Conclusions

Then you could pop one open
1. Introduction
2. Comparative Analysis
    Select genomes for analysis
    Pan Genome Analysis

    Etc. 
3. Modeling
4. Conclusions

Makes it much easier to navigate.

**Comment by briehl** [comment]
That's a good point.

Following along with the chapters idea, it would be nice to have nested groups that can be individually collapsed. So, under your "Comparative Analysis" chapter, that could also include all the code/apps/outputs as well as the markdown. I think that'll be a tricky bit of UX to design, but it could be pretty useful.

Minor tangent - there are a few other IPython visual elements that are effectively hidden right now that we need to bring back (along with some obvious way to use and manipulate them in the KBase cell context), including page anchors and such.

**Comment by aparkin** [comment]
Agreed to all! Er.. How tricky.. And how does it muck with the ipython upgrade path?

Please excuse any terseness or errors. This is sent from my mobile.

-- 
Adam Paul Arkin
Dean A. Richard Newton Memorial Chair
-------------------------------------
Director, Physical Biosciences Division
E.O. Lawrence Berkeley National Laboratory

Professor, Department of Bioengineering
University of California
Berkeley, CA, 94720

CEO/CSO DOE Systems Biology Knowledgebase, http://kbase.us 
Director, Berkeley Synthetic Biology Institute,http://synbio.berkeley.edu
PI and Co-director, Virtual Institute of Microbial Stress and Survival,http://vimss.lbl.gov
Investigator, Energy Biosciences Institute,http://energybiosciencesinstitute.org

Office: 512C Energy Biosciences Building (Berkeley Campus)
Mailing address:
E.O. Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 955-512L
Berkeley, CA 94720

Contact:
W: http://genomics.lbl.gov
V: 510-495-2366
C: 510-206-1389
F: 510-486-6219

Assistant:
Gwyneth A. Terry
V: 510-495-2116
E: GATerry@lbl.gov
-------------------------------------
