### ISSUE TITLE
what do the buttons in the data tab do?

### ISSUE THREAD

**Issue by kkellerlbl** [kbase/narrative#140]
Shane, Dan, and I couldn't figure out what the buttons on the Data tab do without clicking on them (the search, sort, filter, and add buttons).

**Comment by msneddon** [comment]
tooltips now appear above these controls in 6dbb4d6.

**Comment by danielolson5** [comment]
The -> button to open the right panel should probably be more obvious given the functionality behind it.  

Maybe the right panel can open automatically when the mouse is over the sidebar. Alternately, the button to open the right panel could be a large button vertically along the right side of the sidebar, 1/3 the height of the sidebar.
