### ISSUE TITLE
Installing issues

### ISSUE THREAD

**Issue by bio-boris** [kbase/narrative#1429]
Installation fails, so you have to
1) Source the narr-venv
2) pip install clustergrammer_widget
3) pip install pandas
4) pip install sklearn

Then installation ./scripts/install_narrative.sh -v narr-venv succeeds without errors

Maybe the solution is to add these to the requirements.txt?

**Comment by briehl** [comment]
Adding those to requirements.txt causes problems when building the image - they're already part of the base image with conda, and adding them to the built narrative image breaks things.

Instead, we could inject them to the build script. Shouldn't be hard - I can probably get to that next week.

**Comment by briehl** [comment]
(he said 7 months ago...)
This has been solved in the Python 3 branch of Narrative, which I'm hoping we migrate too soon. I'll patch the current one to play nicer soon.

**Comment by jayrbolton** [comment]
Here's what worked for me. In the `develop` branch as of 12/12/2019, make sure you make a virtualenv for python2  not python3:
```sh
virtualenv --python=$(which python2) narrative_venv
source narrative_env/bin/activate
pip install clustergrammer_widget pandas sklearn
./scripts/install_narrative.sh
kbase-narrative
```

**Comment by briehl** [comment]
Cleared up with the update to Python 3. The install script and dependency management now uses conda/miniconda. So this is outdated.
