### ISSUE TITLE
Can't copy from Examples tab

### ISSUE THREAD

**Issue by briehl** [kbase/narrative#1489]
Copying data from the Examples tab from the data slideout doesn't work in 3.11.2 (the big data panel update). Clicking the Add button doesn't do anything.

**Comment by psdehal** [comment]
I have the same issue. Add button works from the other tabs and the example add works on the production version.

**Comment by briehl** [comment]
Got a fix. Working up a PR now.

BTW, maybe we could migrate to Github issues, at least for internal dev? They're more open than either Trello or JIRA, and we're not using JIRA for internal tracking anymore.
