### ISSUE TITLE
Graphic design tweaks round 1

### ISSUE THREAD

**Issue by sspoon** [kbase/narrative#161]
These are mostly minor and is not a comprehensive list. But some of the consistency issues should be fixed.

Design Throughout
- Separator lines are too pale, they should be #CECECE
- for all the lists (the data list, the apps & methods list), remove the separator at the very top

Header
- put spacing or even divider between account icon and narrative buttons
- make the buttons round if we are mostly going for round buttons 
- after saving the narrative, make the title non-italic (italic for unsaved only)

Left Panel
- Make the tabs color #2196F3
- Make inactive tab text color #BBDEFB 
- Make active tab indicator #10CE34

Data Panel
- The “Add Data” button, change colors to #E53935 on hover

Data Slideout
- the “add” buttons should be consistent (in example data, the button is persistent, in other tabs, they appear on hover)
- icons need to be the same as the icons in the data panel
- filter options and searching needs to be consistent through all the tabs
- import, need to fix the tabs (should not show the first level of tabs when showing the secondary level of tabs, see the mockups)

Working/Notebook Area
- bottom buttons are too subtle, maybe try blue #2196F3 (with opacity still 0.5)
- the markdown cells shouldn’t have that top panel styling like that, it can be a simple horizontal line. There's sort of mix of styles going on in general.

**Comment by sspoon** [comment]
Currently running step in an app
- The red makes it seem like there might be an error, try \#2196F3 (blue)
- It would be nice in addition to add some kind of slightly animated icon

**Comment by briehl** [comment]
I think these are almost completely finished now. The only ones that are still there are:
  - __after saving the narrative, make the title non-italic (italic for unsaved only)__
    This is tricky because currently the IPython widget handles that. But I think some style rules can be applied, or it can be refactored. Either way, maybe this one can wait until after upgrading to IPython 3.0, which might make things easier?
  - __import, need to fix the tabs (should not show the first level of tabs when showing the secondary level of tabs, see the mockups)__
