### ISSUE TITLE
Feature Request: rehabilitated spec viewer in narrative

### ISSUE THREAD

**Issue by n1mus** [kbase/narrative#1613]
So I saw that there was at one point functioning software for this, and it would greatly enhance a kb-sdk dev's workflow if they could quickly test out parameter combinations to get the perfect UI.

I personally have wanted very specific UI's for my app cells, but have had to iteratively enumerate parameter combinations, register, and even run to see what's passed in; and after a number of apps, it's ad nauseum and not great for my mental health! I would like to concentrate my work more on coding, testing, and analysis, not something that would depress even an intern :(

**Comment by MrCreosote** [comment]
You're saying the code in this narrative no longer works? https://narrative.kbase.us/narrative/28370

**Comment by n1mus** [comment]
requested view access

i was referring to https://ci.kbase.us/narrative/45686

**Comment by MrCreosote** [comment]
both narratives just use `generate_app_cell`. 

What's broken about it?

**Comment by n1mus** [comment]
oh wow it's working now!
i'm guessing there's no way to see what gets passed in since it won't run?

**Comment by MrCreosote** [comment]
Update the inputs in the ui and then `View code` in the dropdown menu

**Comment by n1mus** [comment]
ah right.
