### ISSUE TITLE
possible bug in method loadState

### ISSUE THREAD

**Issue by msneddon** [kbase/narrative#339]
I think there might be a bug here: https://github.com/kbase/narrative/blob/develop/src/notebook/ipython_profiles/profile_narrative/kbase_templates/static/kbase/js/widgets/narrative_core/kbaseNarrativeMethodCell.js#L250.  

The 'changeState' method seems to assume the state is string, but here we are passing 'runningState', which is an object.  When I was testing on my fork calling this function directly it generates an error.  What's strange though is that I assume the load state was properly working currently in the narrative... Or maybe the runState of a method is set in a different way?  Perhaps using the load state that assumes the state contains only parameters.

**Comment by briehl** [comment]
Obsolete - that widget isn't used anymore.
